#!/usr/bin/env python3

import os
import sys

module = '5EV'
if module == '2EG':
    base_addr = '0xa003'
else:
    base_addr = '0x8002'

if sys.argv[2] == 'on':
    bit = '1'
elif sys.argv[2] == 'off':
    bit = '0'
else:
    bit = '0'

if sys.argv[1] == '0':
    addr = base_addr + '0010 '
elif sys.argv[1] == '1':
    addr = base_addr + '0014 '
elif sys.argv[1] == '2':
    addr = base_addr + '0018 '
elif sys.argv[1] == '3':
    addr = base_addr + '001c '
elif sys.argv[1] == '4':
    addr = base_addr + '0020 '
elif sys.argv[1] == '5':
    addr = base_addr + '0024 '
else:
    addr = base_addr + '00fc '

os.system('poke ' + addr  + bit)
print ('Powering WIB ' + sys.argv[1] + ' ' + sys.argv[2])