# meta-custom/conf/distro/ptc-micro-distro.conf

DISTRO = "ptc-micro-distro"
DISTRO_NAME = "PTC Ultra-Minimal BusyBox Linux"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "micro"

INIT_MANAGER = "mdev-busybox"

VIRTUAL-RUNTIME_initscripts = "initscripts"
VIRTUAL-RUNTIME_init_manager = "busybox"
VIRTUAL-RUNTIME_login_manager = "busybox"
VIRTUAL-RUNTIME_dev_manager = "busybox-mdev"

PACKAGE_CLASSES ?= "package_ipk"

USE_NLS = "no"
IMAGE_LINGUAS = ""

DISTRO_FEATURES = " \
    sysvinit \
    ipv4 \
    ipv6 \
    usrmerge \
"

DISTRO_FEATURES_BACKFILL_CONSIDERED += "systemd"

DISTRO_FEATURES:remove = " \
    systemd \
    alsa \
    bluetooth \
    nfc \
    3g \
    nfs \
    zeroconf \
    x11 \
    wayland \
    opengl \
    vulkan \
    pulseaudio \
"

VOLATILE_LOG_DIR = "yes"