# meta-ptc/conf/distro/ptc-nano-distro.conf

DISTRO = "ptc-nano-distro"
DISTRO_NAME = "PTC Linux with musl"
DISTRO_VERSION = "1.0.0"
DISTRO_CODENAME = "nano"

# Use musl libc instead of glibc
TCLIBC = "musl"

# use glibc to build the microblaze and fsbl stuff
#TCLIBC:target-microblaze = "newlib"

FSBL_DEPENDS = ""
PMU_DEPENDS = ""
FSBL_MCDEPENDS = ""
PMU_MCDEPENDS = ""

# The recipe appends .elf, so omit the extension here
FSBL_FILE = "${TOPDIR}/../prebuilts/fsbl-zynqmp-ptc"
PMU_FILE  = "${TOPDIR}/../prebuilts/pmu-firmware-zynqmp-ptc"

PMU_FIRMWARE_DEPLOY_DIR = "${TOPDIR}/../prebuilts"
FSBL_DEPLOY_DIR = "${TOPDIR}/../prebuilts"

PMU_FIRMWARE_IMAGE_NAME = "pmu-firmware-zynqmp-ptc.elf"
FSBL_IMAGE_NAME = "fsbl-zynqmp-ptc.elf"

#FSBL_FILE = "/workdir/prebuilts/fsbl-zynqmp-ptc.elf"
#PMU_FIRMWARE_IMAGE_BINARY = "/workdir/prebuilts/pmu-firmware-zynqmp-ptc.elf"

# Blindfold BitBake so it never tries to parse or build the firmware recipes from meta-xilinx
#BBMASK += "meta-xilinx.*/recipes-bsp/embeddedsw/fsbl-firmware_.*"
#BBMASK += "meta-xilinx.*/recipes-bsp/embeddedsw/pmu-firmware_.*"


# Use BusyBox for init and mdev for device management
INIT_MANAGER = "mdev-busybox"

VIRTUAL-RUNTIME_initscripts = "initscripts"
VIRTUAL-RUNTIME_init_manager = "busybox"
VIRTUAL-RUNTIME_login_manager = "busybox"
VIRTUAL-RUNTIME_dev_manager = "busybox-mdev"

PACKAGE_CLASSES ?= "package_ipk"

USE_NLS = "no"
IMAGE_LINGUAS = ""

DISTRO_FEATURES = " \
    sysvinit \
    ipv4 \
    ipv6 \
    usrmerge \
"

DISTRO_FEATURES_BACKFILL_CONSIDERED += "systemd"

DISTRO_FEATURES:remove = " \
    systemd \
    alsa \
    bluetooth \
    nfc \
    3g \
    nfs \
    zeroconf \
    x11 \
    wayland \
    opengl \
    vulkan \
    pulseaudio \
"

VOLATILE_LOG_DIR = "yes"